version: '3.8'
services:
  windows_11_service:
    container_name: windows_11_container
    image: windows_11_image
    networks:
      - windows_network
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - ENV_VAR1=value1
      - ENV_VAR2=value2
    ports:
      - "8080:8080"
    command: ["./start_container.sh"]

networks:
  windows_network:
    driver: bridge